namespace Pulso
{
    // Traduções da janela de Configurações: { português (como está no código), inglês, espanhol }
    static partial class Idioma
    {
        static readonly string[,] tConfiguracoes =
        {
            // janela, barra lateral e aviso
            { "Contas", "Accounts", "Cuentas" },
            { "Aparência", "Appearance", "Apariencia" },
            { "Geral", "General", "General" },
            { "Pulso — Configurações", "Pulso — Settings", "Pulso — Configuración" },
            { "Encerrar o Pulso", "Quit Pulso", "Salir de Pulso" },
            { "Salvo", "Saved", "Guardado" },

            // atalho
            { "Cancelar", "Cancel", "Cancelar" },
            { "Gravar novo atalho", "Record new shortcut", "Grabar nuevo atajo" },
            { "Pronto: {0} mostra e oculta a cápsula.", "Done: {0} shows and hides the capsule.", "Listo: {0} muestra y oculta la cápsula." },
            { "{0} já é usado pelo Windows ou por outro programa — o atalho anterior continua valendo.", "{0} is already used by Windows or another program — the previous shortcut still applies.", "{0} ya lo usa Windows u otro programa — el atajo anterior sigue vigente." },
            { "Restaurar {0}", "Restore {0}", "Restaurar {0}" },
            { "{0} está em uso por outro programa — o atalho anterior continua valendo.", "{0} is in use by another program — the previous shortcut still applies.", "{0} está en uso por otro programa — el atajo anterior sigue vigente." },
            { "Pressione as teclas…", "Press the keys…", "Presiona las teclas…" },

            // Contas
            { "Sem leitura ainda.", "No reading yet.", "Sin lectura todavía." },
            { "exato {0}", "exact {0}", "exacto {0}" },
            { "sem leitura exata", "no exact reading", "sin lectura exacta" },
            { "Instalado neste computador — ative para ler o consumo", "Installed on this computer — turn it on to read usage", "Instalado en este equipo — actívalo para leer el consumo" },
            { "Estimativa ao vivo", "Live estimate", "Estimación en vivo" },
            { "Barra de status do Claude Code", "Claude Code status line", "Barra de estado de Claude Code" },
            { "Estimativa ao vivo: o anel anda a cada resposta, sem esperar o servidor (o número aparece com “~”).", "Live estimate: the ring moves with every response, without waiting for the server (the number shows with “~”).", "Estimación en vivo: el anillo avanza con cada respuesta, sin esperar al servidor (el número aparece con “~”)." },
            { "Barra de status: o Claude Code já usa outra barra, e o Pulso não a substitui.", "Status line: Claude Code already uses another status line, and Pulso won't replace it.", "Barra de estado: Claude Code ya usa otra barra, y Pulso no la reemplaza." },
            { "Barra de status: quando você usa o Claude Code no terminal, o número exato chega a cada resposta.", "Status line: when you use Claude Code in the terminal, the exact number arrives with every response.", "Barra de estado: cuando usas Claude Code en la terminal, el número exacto llega con cada respuesta." },
            { "Leitura da cápsula", "Capsule reading", "Lectura de la cápsula" },
            { "Automático", "Automatic", "Automático" },
            { "Limite de 5 horas", "5-hour limit", "Límite de 5 horas" },
            { "Limite semanal", "Weekly limit", "Límite semanal" },
            { "Dados do modelo", "Model data", "Datos del modelo" },
            { "Modelos Gemini", "Gemini models", "Modelos Gemini" },
            { "Modelos Claude e GPT", "Claude and GPT models", "Modelos Claude y GPT" },
            { "Pelo menos um provedor permanece selecionado para que a cápsula nunca fique vazia.", "At least one provider stays selected so the capsule is never empty.", "Al menos un proveedor permanece seleccionado para que la cápsula nunca quede vacía." },
            { "Conectado", "Connected", "Conectado" },
            { "Estes não têm anel. Ative um e ele entra no fim da lista acima; um provedor não instalado neste computador não aparece na cápsula.", "These have no ring. Turn one on and it joins the end of the list above; a provider not installed on this computer doesn't appear in the capsule.", "Estos no tienen anillo. Activa uno y entrará al final de la lista de arriba; un proveedor no instalado en este equipo no aparece en la cápsula." },
            { "Não conectado", "Not connected", "No conectado" },

            // Aparência
            { "A cápsula fica aberta com todas as leituras visíveis.", "The capsule stays open with all readings visible.", "La cápsula queda abierta con todas las lecturas visibles." },
            { "Uma pequena cápsula na borda da tela que abre quando você chega nela.", "A small capsule on the edge of the screen that opens when you reach it.", "Una pequeña cápsula en el borde de la pantalla que se abre cuando llegas a ella." },
            { "A cápsula some; o Pulso continua contando seu uso e o ícone da bandeja fica visível.", "The capsule disappears; Pulso keeps tracking your usage and the system tray icon stays visible.", "La cápsula desaparece; Pulso sigue contando tu uso y el icono de la bandeja del sistema queda visible." },
            { "Cápsula e anéis menores, para ocupar o mínimo da borda. O texto dos cartões continua do tamanho do Médio.", "Smaller capsule and rings, to take up as little of the edge as possible. Card text stays at the Medium size.", "Cápsula y anillos más pequeños, para ocupar lo mínimo del borde. El texto de las tarjetas sigue con el tamaño Mediano." },
            { "O tamanho com que a cápsula foi desenhada.", "The size the capsule was designed at.", "El tamaño con el que se diseñó la cápsula." },
            { "Mais fácil de ler de relance, e mais difícil de ignorar.", "Easier to read at a glance, and harder to ignore.", "Más fácil de leer de un vistazo, y más difícil de ignorar." },
            { "A cápsula e esta janela seguem a cor dos aplicativos do Windows.", "The capsule and this window follow the Windows app color mode.", "La cápsula y esta ventana siguen el color de las aplicaciones de Windows." },
            { "Cápsula e cartão claros, independentemente da configuração do Windows.", "Light capsule and card, regardless of the Windows setting.", "Cápsula y tarjeta claras, sin importar la configuración de Windows." },
            { "A cápsula escura, independentemente da configuração do Windows.", "Dark capsule, regardless of the Windows setting.", "La cápsula oscura, sin importar la configuración de Windows." },
            { "Um anel por provedor, mostrando o limite principal. A cota semanal permanece no cartão ao passar o cursor.", "One ring per provider, showing the main limit. The weekly quota stays on the card shown on hover.", "Un anillo por proveedor, que muestra el límite principal. La cuota semanal sigue en la tarjeta al pasar el cursor." },
            { "Um anel mais fino para o limite semanal, desenhado dentro do principal. Ele compartilha o espaço com o indicador de atividade.", "A thinner ring for the weekly limit, drawn inside the main one. It shares the space with the activity indicator.", "Un anillo más fino para el límite semanal, dibujado dentro del principal. Comparte el espacio con el indicador de actividad." },
            { "Um anel mais fino para o limite semanal, desenhado ao redor do principal, no espaço entre o anel e a borda da cápsula.", "A thinner ring for the weekly limit, drawn around the main one, in the space between the ring and the edge of the capsule.", "Un anillo más fino para el límite semanal, dibujado alrededor del principal, en el espacio entre el anillo y el borde de la cápsula." },
            { "Exibição", "Display", "Visualización" },
            { "Sempre exibir", "Always show", "Siempre visible" },
            { "Exibir ao passar o cursor", "Show on hover", "Al pasar el cursor" },
            { "Ocultar", "Hide", "Oculta" },
            { "Cápsula adaptável", "Adaptive capsule", "Cápsula adaptable" },
            { "Enquanto está recolhida, a cápsula acompanha o que está atrás dela: clara sobre fundo escuro, preta sobre fundo claro, para continuar fácil de achar. Para isso, o Pulso lê uma faixa fina da tela ao lado da cápsula duas vezes por segundo e guarda só o brilho médio.", "While collapsed, the capsule adapts to what is behind it: light on dark backgrounds, black on light backgrounds, so it stays easy to find. To do this, Pulso reads a thin strip of the screen next to the capsule twice per second and keeps only the average brightness.", "Mientras está recogida, la cápsula se adapta a lo que tiene detrás: clara sobre fondo oscuro, negra sobre fondo claro, para seguir siendo fácil de encontrar. Para ello, Pulso lee una franja fina de la pantalla junto a la cápsula dos veces por segundo y guarda solo el brillo medio." },
            { "Tamanho", "Size", "Tamaño" },
            { "Pequeno", "Small", "Pequeño" },
            { "Médio", "Medium", "Mediano" },
            { "Grande", "Large", "Grande" },
            { "Tema", "Theme", "Tema" },
            { "Do sistema", "System", "Sistema" },
            { "Clara", "Light", "Claro" },
            { "Escura", "Dark", "Oscuro" },
            { "Anel semanal", "Weekly ring", "Anillo semanal" },
            { "Desativado", "Off", "Desactivado" },
            { "Dentro", "Inside", "Dentro" },
            { "Fora", "Outside", "Fuera" },
            { "Anel semanal tracejado", "Dashed weekly ring", "Anillo semanal discontinuo" },
            { "Ritmo do dia no Claude", "Daily pace on Claude", "Ritmo diario en Claude" },
            { "O anel do Claude passa a mostrar o uso da semana contra a parte liberada até hoje: 1/7 da cota por dia, contado a partir da abertura da semana. Gastando no ritmo, o anel só chega a 100% no fim de cada dia. A sessão de 5 horas continua no cartão.", "Claude's ring shows the week's usage against the share unlocked so far: 1/7 of the quota per day, counted from the start of the week. Spending on pace, the ring only reaches 100% at the end of each day. The 5-hour session stays on the card.", "El anillo de Claude pasa a mostrar el uso de la semana frente a la parte liberada hasta hoy: 1/7 de la cuota por día, contado desde el inicio de la semana. Gastando al ritmo, el anillo solo llega al 100% al final de cada día. La sesión de 5 horas sigue en la tarjeta." },
            { "Consumo por projeto no cartão", "Usage per project on the card", "Consumo por proyecto en la tarjeta" },
            { "O cartão do Claude e do Codex mostra quanto da sessão de 5 horas veio de cada pasta de projeto. Conta só o uso deste computador.", "The Claude and Codex card shows how much of the 5-hour session came from each project folder. Counts only usage on this computer.", "La tarjeta de Claude y Codex muestra cuánto de la sesión de 5 horas vino de cada carpeta de proyecto. Solo cuenta el uso de este equipo." },
            { "Borda", "Edge", "Borde" },
            { "Esquerda", "Left", "Izquierda" },
            { "Direita", "Right", "Derecha" },
            { "Superior", "Top", "Superior" },
            { "Inferior", "Bottom", "Inferior" },
            { "{0} · principal", "{0} · main", "{0} · principal" },
            { "Tela", "Screen", "Pantalla" },
            { "Arrastável", "Draggable", "Arrastrable" },
            { "Segure Alt e arraste a cápsula, ou arraste a engrenagem ou os pontinhos ao lado dela, para levá-la pelas bordas da tela. Cada borda lembra onde você a deixou. Recentralizar a põe de volta no meio da borda em que está.", "Hold Alt and drag the capsule, or drag the gear or the dots next to it, to move it along the screen edges. Each edge remembers where you left it. Recenter puts it back in the middle of its current edge.", "Mantén Alt y arrastra la cápsula, o arrastra el engranaje o los puntitos junto a ella, para llevarla por los bordes de la pantalla. Cada borde recuerda dónde la dejaste. Recentrar la devuelve al centro del borde en el que está." },
            { "Recentralizar", "Recenter", "Recentrar" },
            { "A cápsula fica fixa no meio da borda escolhida acima. Ao passar o cursor na orelha de baixo aparece só a engrenagem das configurações, sem os pontinhos de arrastar.", "The capsule stays fixed in the middle of the edge chosen above. Hovering over the bottom tab shows only the settings gear, without the drag dots.", "La cápsula queda fija en el centro del borde elegido arriba. Al pasar el cursor por la pestaña inferior solo aparece el engranaje de la configuración, sin los puntitos de arrastre." },
            { "Degrau seco", "Hard step", "Escalón seco" },
            { "Rampa de cor", "Color ramp", "Rampa de color" },
            { "Cápsula", "Capsule", "Cápsula" },
            { "Limites de uso", "Usage limits", "Límites de uso" },
            { "Transição de cor", "Color transition", "Transición de color" },
            { "A cor muda continuamente de verde para vermelho em toda a faixa e fica amarela no limite de atenção abaixo.", "The color shifts continuously from green to red across the whole range and turns yellow at the warning limit below.", "El color cambia de forma continua de verde a rojo en todo el rango y se vuelve amarillo en el límite de atención de abajo." },
            { "Verde, amarelo e vermelho permanecem cores sólidas e mudam de uma para outra nos limites abaixo.", "Green, yellow and red stay solid colors and switch from one to the next at the limits below.", "Verde, amarillo y rojo siguen siendo colores sólidos y cambian de uno a otro en los límites de abajo." },
            { "Limite de atenção", "Warning limit", "Límite de atención" },
            { "Limite crítico", "Critical limit", "Límite crítico" },
            { "Com a rampa de cor ativada, o anel só fica vermelho em 100%, então o limite crítico vale no modo Degrau seco.", "With the color ramp on, the ring only turns red at 100%, so the critical limit applies in Hard step mode.", "Con la rampa de color activada, el anillo solo se vuelve rojo al 100%, así que el límite crítico vale en el modo Escalón seco." },
            { "Restaurar padrões", "Restore defaults", "Restaurar predeterminados" },
            { "App", "App", "Aplicación" },
            { "Ícone do app", "App icon", "Icono de la app" },
            { "Bandeja do sistema", "System tray", "Bandeja del sistema" },
            { "Nenhum", "None", "Ninguno" },
            { "Com a cápsula oculta, o ícone na bandeja fica, para você não perder o acesso.", "With the capsule hidden, the tray icon stays so you don't lose access.", "Con la cápsula oculta, el icono de la bandeja se queda para que no pierdas el acceso." },
            { "O ícone na bandeja mostra um mini anel com o consumo atual.", "The tray icon shows a mini ring with current usage.", "El icono de la bandeja muestra un mini anillo con el consumo actual." },
            { "Sem ícone na bandeja; a cápsula é o único acesso.", "No tray icon; the capsule is the only way in.", "Sin icono en la bandeja; la cápsula es el único acceso." },

            // Geral
            { "Idioma", "Language", "Idioma" },
            { "Abrir o Pulso ao entrar no Windows", "Open Pulso when you sign in to Windows", "Abrir Pulso al iniciar sesión en Windows" },
            { "O Pulso abre sozinho toda vez que você entra neste computador e fica quieto em segundo plano. Desative e você precisará abri-lo manualmente.", "Pulso opens on its own every time you sign in to this computer and stays quietly in the background. Turn it off and you'll need to open it manually.", "Pulso se abre solo cada vez que inicias sesión en este equipo y se queda tranquilo en segundo plano. Desactívalo y tendrás que abrirlo manualmente." },
            { "Atalho para mostrar e ocultar a cápsula", "Shortcut to show and hide the capsule", "Atajo para mostrar y ocultar la cápsula" },
            { "Teclas", "Keys", "Teclas" },
            { "Pressione a combinação: Ctrl, Alt, Shift ou Win com outra tecla, ou uma tecla de F1 a F24. Esc cancela.", "Press the combination: Ctrl, Alt, Shift or Win with another key, or a key from F1 to F24. Esc cancels.", "Presiona la combinación: Ctrl, Alt, Shift o Win con otra tecla, o una tecla de F1 a F24. Esc cancela." },
            { "Desativado.", "Off.", "Desactivado." },
            { "Mostra e oculta a cápsula de qualquer lugar.", "Shows and hides the capsule from anywhere.", "Muestra y oculta la cápsula desde cualquier lugar." },
            { "{0} está em uso por outro programa — grave outra combinação.", "{0} is in use by another program — record another combination.", "{0} está en uso por otro programa — graba otra combinación." },
            { "Notificações", "Notifications", "Notificaciones" },
            { "Avisos de renovação", "Reset alerts", "Avisos de renovación" },
            { "Mostra um cartão ao lado da cápsula quando o Claude ou o Codex renova uma janela depois de pelo menos 10% de uso. O cartão aparece mesmo com a cápsula oculta.", "Shows a card next to the capsule when Claude or Codex resets a window after at least 10% usage. The card appears even with the capsule hidden.", "Muestra una tarjeta junto a la cápsula cuando Claude o Codex renueva una ventana después de al menos un 10% de uso. La tarjeta aparece incluso con la cápsula oculta." },
            { "Aviso de limite", "Limit alert", "Aviso de límite" },
            { "Avisa quando uma janela chega a 80%, a 95% e ao limite, uma vez por janela — sempre pelo valor exato, nunca pela estimativa.", "Alerts when a window reaches 80%, 95% and the limit, once per window — always from the exact value, never the estimate.", "Avisa cuando una ventana llega al 80%, al 95% y al límite, una vez por ventana — siempre por el valor exacto, nunca por la estimación." },
            { "Aviso de ritmo", "Pace alert", "Aviso de ritmo" },
            { "Avisa quando, no ritmo dos últimos 30 minutos, a sessão de 5 horas vai acabar antes de renovar — com tempo de desacelerar antes dos avisos de 80% e 95%. Uma vez por sessão.", "Alerts when, at the pace of the last 30 minutes, the 5-hour session will run out before it resets — with time to slow down before the 80% and 95% alerts. Once per session.", "Avisa cuando, al ritmo de los últimos 30 minutos, la sesión de 5 horas se va a agotar antes de renovarse — con tiempo para frenar antes de los avisos del 80% y 95%. Una vez por sesión." },
            { "Sessão terminou", "Session finished", "Sesión terminada" },
            { "Avisa quando o Claude ou o Codex termina uma resposta que levou pelo menos 10 segundos — a não ser que você já esteja na janela dela. Clicar no cartão leva até a janela.", "Alerts when Claude or Codex finishes a response that took at least 10 seconds — unless you're already in its window. Clicking the card takes you to the window.", "Avisa cuando Claude o Codex termina una respuesta que tardó al menos 10 segundos — a menos que ya estés en su ventana. Al hacer clic en la tarjeta vas a la ventana." },
            { "Sessão esperando você", "Session waiting for you", "Sesión esperándote" },
            { "Avisa quando uma sessão para e pede a sua resposta (permissão, pergunta).", "Alerts when a session stops and asks for your reply (permission, question).", "Avisa cuando una sesión se detiene y pide tu respuesta (permiso, pregunta)." },
            { "Som dos avisos", "Alert sound", "Sonido de los avisos" },
            { "Pré-visualizar o cartão", "Preview the card", "Vista previa de la tarjeta" },
            { "Pré-visualizar", "Preview", "Vista previa" },
            { "Atualizações", "Updates", "Actualizaciones" },
            { "Pasta de dados", "Data folder", "Carpeta de datos" },
            { "Abrir pasta", "Open folder", "Abrir carpeta" },
            { "Tudo o que o Pulso guarda fica numa pasta: configurações, estado, índice de custo e log. Nenhuma credencial.", "Everything Pulso stores lives in one folder: settings, state, cost index and log. No credentials.", "Todo lo que Pulso guarda está en una carpeta: configuración, estado, índice de costos y registro. Ninguna credencial." },
            { "Desinstalar o Pulso", "Uninstall Pulso", "Desinstalar Pulso" },
            { "Desinstalar…", "Uninstall…", "Desinstalar…" },
            { "Também dá para desinstalar em Configurações › Aplicativos do Windows. Você escolhe se as suas configurações ficam.", "You can also uninstall it from Windows Settings › Apps. You choose whether your settings are kept.", "También puedes desinstalarlo en Configuración › Aplicaciones de Windows. Tú eliges si se conserva tu configuración." },

            // Atualizações
            { "Versão", "Version", "Versión" },
            { "Para receber atualizações por aqui, instale o Pulso pelo instalar.cmd da pasta do projeto clonada do GitHub.", "To get updates here, install Pulso with instalar.cmd from the project folder cloned from GitHub.", "Para recibir actualizaciones aquí, instala Pulso con el instalar.cmd de la carpeta del proyecto clonada de GitHub." },
            { "Instalar atualização", "Install update", "Instalar actualización" },
            { "Procurando…", "Checking…", "Buscando…" },
            { "Procurar atualização", "Check for updates", "Buscar actualizaciones" },
            { "Versão nova no GitHub ({0}). Instalar atualização baixa, compila e reabre o Pulso em alguns segundos.", "New version on GitHub ({0}). Install update downloads, builds and reopens Pulso in a few seconds.", "Nueva versión en GitHub ({0}). Instalar actualización descarga, compila y reabre Pulso en unos segundos." },
            { "Você está com a versão mais recente.", "You're on the latest version.", "Tienes la versión más reciente." },
            { "Consultando o GitHub…", "Checking GitHub…", "Consultando GitHub…" },
            { "O Pulso procura sozinho 2 minutos depois de abrir e a cada 12 horas, sem interromper você.", "Pulso checks on its own 2 minutes after opening and every 12 hours, without interrupting you.", "Pulso busca solo 2 minutos después de abrirse y cada 12 horas, sin interrumpirte." },
        };
    }
}
